
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
  logs:
    custom_components.green_shift: debug

# Lovelace UI configuration (YAML mode)
lovelace:
  mode: yaml
  resources: []
  dashboards:
    lovelace-green-shift:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Green Shift
      icon: mdi:leaf

# Load helpers (separated by type)
input_number: !include input_numbers.yaml
input_select: !include input_selects.yaml
input_boolean: !include input_booleans.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
