energy_saving_target:
  name: "Savings Target (%)"
  unit_of_measurement: "%"
  min: 0
  max: 30
  step: 5
  mode: slider
  icon: mdi:target
  initial: 15

electricity_price:
  name: "Electricity Price (Price/kWh)"
  unit_of_measurement: "Price/kWh"
  min: 0.10
  max: 0.50
  step: 0.01
  mode: box
  icon: mdi:currency-usd
  initial: 0.25
